mc_version: "1.18.2"
mods:
  - "krypton"
  - "sodium"
  - "lithium"
  - "fabric-api"
  - "lazydfu"
  - "indium"
  - "modmenu"
  - "sodium-extra"
  - "lambdynamiclights"
  - "starlight"
  - "ok-zoomer"
  - "ferrite-core"
  - "dynamic-fps"
  - "lambdabettergrass"